package android.view.accessibility;import android.graphics.Rect;import java.util.*;public class AccessibilityNodeInfo{
public static final int ACTION_CLICK=16,ACTION_LONG_CLICK=32,ACTION_DISMISS=1048576,ACTION_SCROLL_FORWARD=4096;
public Object logicalToken;@Override public boolean equals(Object other){return this==other || logicalToken!=null && other instanceof AccessibilityNodeInfo n && logicalToken==n.logicalToken;}@Override public int hashCode(){return logicalToken==null?System.identityHashCode(this):System.identityHashCode(logicalToken);}
public boolean refreshValid=true;public int refreshCalls;public Runnable onRefresh;public boolean refresh(){refreshCalls++;if(onRefresh!=null){Runnable r=onRefresh;onRefresh=null;r.run();}return refreshValid;}
public CharSequence text,desc,name="android.view.View",pkg="host.example";public String id;public Rect bounds=new Rect(0,0,100,50);public boolean visible=true,clickable=true,enabled=true,scrollable,password,editable;public int window=1,childReads,fastReads,clicks,recycles;
public AccessibilityNodeInfo parent;public List<AccessibilityNodeInfo> children=new ArrayList<>();public AccessibilityNodeInfo add(AccessibilityNodeInfo n){children.add(n);n.parent=this;n.pkg=pkg;return this;}
public CharSequence getText(){return text;}public CharSequence getContentDescription(){return desc;}public CharSequence getClassName(){return name;}public CharSequence getPackageName(){return pkg;}public String getViewIdResourceName(){return id;}
public boolean isVisibleToUser(){return visible;}public boolean isEnabled(){return enabled;}public boolean isClickable(){return clickable;}public boolean isLongClickable(){return clickable;}public boolean isFocusable(){return false;}public boolean isCheckable(){return false;}public boolean isChecked(){return false;}public boolean isEditable(){return editable;}public boolean isPassword(){return password;}public boolean isScrollable(){return scrollable;}
public void getBoundsInScreen(Rect r){r.set(bounds);}public int getChildCount(){return children.size();}public AccessibilityNodeInfo getChild(int i){childReads++;return children.get(i);}public AccessibilityNodeInfo getParent(){return parent;}public int getWindowId(){return window;}
public int getActions(){return 0;}public boolean performAction(int a){clicks++;return true;}public void recycle(){recycles++;}public List<AccessibilityAction> getActionList(){return Collections.emptyList();}
public static class AccessibilityAction{public int getId(){return 0;}}
private List<AccessibilityNodeInfo> flatten(){List<AccessibilityNodeInfo> all=new ArrayList<>();for(AccessibilityNodeInfo n:children){all.add(n);all.addAll(n.flatten());}return all;}
public List<AccessibilityNodeInfo> findAccessibilityNodeInfosByText(String v){fastReads++;List<AccessibilityNodeInfo> out=new ArrayList<>();for(AccessibilityNodeInfo n:flatten())if((n.text!=null&&n.text.toString().contains(v))||(n.desc!=null&&n.desc.toString().contains(v)))out.add(n);return out;}
public List<AccessibilityNodeInfo> findAccessibilityNodeInfosByViewId(String v){fastReads++;List<AccessibilityNodeInfo> out=new ArrayList<>();for(AccessibilityNodeInfo n:flatten())if(v.equals(n.id))out.add(n);return out;}
}